name: kbvqa
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - ca-certificates=2022.4.26
  - certifi=2021.10.8
  - cudatoolkit=10.2.89
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - openssl=1.1.1o
  - pip=21.2.2
  - python=3.7.11
  - pytorch=1.5.1
  - readline=8.1.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.3
  - tk=8.6.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.0.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.12
    - click==8.1.3
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.46.1
    - idna==3.3
    - importlib-metadata==4.11.3
    - joblib==1.1.0
    - markdown==3.3.7
    - nltk==3.6.2
    - oauthlib==3.2.0
    - protobuf==3.20.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyyaml==6.0
    - regex==2022.4.24
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sklearn==0.0
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tqdm==4.62.2
    - typing-extensions==4.2.0
    - urllib3==1.26.9
    - werkzeug==2.1.2
    - zipp==3.8.0